name: test

on: [push, pull_request]

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
        rubygems: latest

    - name: Run RuboCop
      run: bundle exec rubocop

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        gemfile: [rack_2_0, rails_6_0, rails_6_1, rails_7_0]
        include:
          - ruby: '2.6'
            gemfile: rails_5_2
          - ruby: '2.7'
            gemfile: rack_1_0
          - ruby: '2.7'
            gemfile: multi_json
          - ruby: '2.7'
            gemfile: multi_xml
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest

    - name: Run tests
      run: bundle exec rake spec

    - name: Run tests (spec/integration/eager_load)
      # rack_2_0.gemfile is equals to Gemfile
      if: ${{ matrix.gemfile == 'rack_2_0' }}
      run: bundle exec rspec spec/integration/eager_load

    - name: Run tests (spec/integration/multi_json)
      if: ${{ matrix.gemfile == 'multi_json' }}
      run: bundle exec rspec spec/integration/multi_json

    - name: Run tests (spec/integration/multi_xml)
      if: ${{ matrix.gemfile == 'multi_xml' }}
      run: bundle exec rspec spec/integration/multi_xml

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
